# Generated by Django 5.0.2 on 2024-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='category',
            field=models.ManyToManyField(related_name='categories_in_restaurants', to='accounts.productcategory'),
        ),
    ]
