# Generated by Django 5.0.2 on 2024-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurantprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
