# Generated by Django 5.0.2 on 2024-05-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
    ]
