# Generated by Django 5.0.2 on 2024-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
