# Generated by Django 5.0.6 on 2024-05-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_order_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='categories',
            field=models.ManyToManyField(related_name='restaurants', to='accounts.productcategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
