# Generated by Django 5.0.6 on 2024-05-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_order_products_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.orderuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
    ]
