# Generated by Django 5.0.6 on 2024-05-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=30)),
                ('ilçe', models.CharField(max_length=30)),
                ('mahalle', models.CharField(max_length=30)),
                ('sokak', models.CharField(max_length=10)),
                ('adresTarifi', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderuser',
            name='adress',
        ),
        migrations.AddField(
            model_name='orderuser',
            name='adres',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adres'),
        ),
    ]
